name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    
    - name: Install PostgreSQL
      run: |
        sudo apt-get -yqq install postgresql postgresql-contrib libpq-dev

    - name: Build and with Rake
      run: |
        gem install bundle
        bundle install --without development test --jobs 4 --retry 3
        bundle exec rake
